
  //@CF fill in 


export default function Faq3() {
  return (
    <div>
          <h2 className="faq-header">Why are you using AI? </h2>

          <div className="faq-content">
          <p>
            Coming soon...
            Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...
            Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...
            Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...
            Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...
            Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...
            Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...
            Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...
            Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...
            Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...Coming soon...
          </p>
          </div>

         
    </div>
  );
}
